### ISSUE TITLE
tcl/tk is needed in versions 2.2-5.5 and 2.2-5.6

### ISSUE THREAD

**Issue by scimerman** [adrian-bowman/sm#1]
Hi, on the https://cran.r-project.org/web/packages/vioplot/index.html is specified that the tcl/tk package is "Suggested" and not "Required" in order to be installed on a system.
That was true for the versions =< 2.2-5.5, but is not true anymore for the newer versions. Quite a lot of the systems in the production, do not have the needed tcl/tk packages installed (nor entire x11 in that matter), so therefore this difference between suggestion and requirement is quite important.

Error we got, when we are installing with R:

```
installing to /home/scimerman/myprivateR/00LOCK-sm/00new/sm/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning: S3 methods ‘as.character.tclObj’, ‘as.character.tclVar’, ‘as.double.tclObj’, ‘as.integer.tclObj’, ‘as.logical.tclObj’, ‘as.raw.tclObj’, ‘print.tclObj’, ‘[[.tclArray’, ‘[[<-.tclArray’, ‘$.tclArray’, ‘$<-.tclArray’, ‘names.tclArray’, ‘names<-.tclArray’, ‘length.tclArray’, ‘length<-.tclArray’, ‘tclObj.tclVar’, ‘tclObj<-.tclVar’, ‘tclvalue.default’, ‘tclvalue.tclObj’, ‘tclvalue.tclVar’, ‘tclvalue<-.default’, ‘tclvalue<-.tclVar’, ‘close.tkProgressBar’ were declared in NAMESPACE but not found
Error: .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: Tcl/Tk support is not available on this system
Execution halted
ERROR: lazy loading failed for package ‘sm’
* removing ‘/home/scimerman/myprivateR/sm’
* restoring previous ‘/home/scimerman/myprivateR/sm’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp1ya1Yk/remotes7a736fe05c4b/sm’ had non-zero exit status
```

**Comment by adrian-bowman** [comment]
Thanks for the query on this.  I think the problem may be triggered by the presence of
   import(tcltk)
in the NAMESPACE of the sm package.  Although the tcltk package is now part of base R, importing it presumably has references to the underlying Tcl/Tk system which, if that’s not present, will trigger an error.  I have removed the import(tcltk) from the NAMESPACE of sm.  If the tcltk facilities are requested (through the use of panel = TRUE in some function calls) then the tcltk package is loaded in response, through the requireNamespace function.

I hope that solves the problem.  The updated version of sm is now on GitHub and this can be installed from R by
		remotes::install_github("adrian-bowman/sm/sm”)
Please let me know of that fixes the problem.

Best wishes,

Adrian

**Comment by scimerman** [comment]
Dear Adrian,
I ended up using the commands

`require(devtools)
install_github("adrian-bowman/sm", subdir="sm")`



```
Downloading GitHub repo adrian-bowman/sm@HEAD
✔  checking for file ‘/tmp/Rtmpi21cWA/remotes7e642a1c14da/adrian-bowman-sm-a6e8be6/sm/DESCRIPTION’ (627ms)
─  preparing ‘sm’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘sm_2.2-5.7.tar.gz’
```

From the `installed.packages()` it returned that the new sm is version 2.2-5.7
`...
sm          "/groups/umcg-gcc/tmp01/umcg-scimerman/R"                "2.2-5.7"
...`

After that I could also install package vioplot without any problems
`install.packages("vioplot")`

Therefore I confirm this issue resolved :+1:. Hopefully we see it soon in the new R :)
Thank you for a quick response!

Regards,
Sandi
